#!/usr/bin/env python3
import os
import sys
import subprocess

# Temas predefinidos para la interfaz hacker
THEMES = {
    "1": {
        "name": "Toxic Green (Classic Matrix)",
        "banner_color": "82",      # Verde Neón
        "border_color": "82",      # Verde Neón
        "accent_color": "82",      # Verde Neón
        "info_color": "7",         # Blanco
        "header_accent": "198",    # Rosa Neón para 
    },
    "2": {
        "name": "Cyberpunk Neon (Pink/Cyan)",
        "banner_color": "198",     # Rosa/Magenta Neón
        "border_color": "198",     # Rosa Neón
        "accent_color": "39",      # Cian
        "info_color": "7",         # Blanco
        "header_accent": "39",     # Cian
    },
    "3": {
        "name": "Blood Red (Deep Net)",
        "banner_color": "196",     # Rojo Sangre
        "border_color": "196",     # Rojo
        "accent_color": "196",     # Rojo
        "info_color": "7",         # Blanco
        "header_accent": "220",    # Dorado/Amarillo
    },
    "4": {
        "name": "Ghost Cyan (Ice Cold)",
        "banner_color": "51",      # Cian Brillante
        "border_color": "51",      # Cian
        "accent_color": "45",      # Azul Claro
        "info_color": "7",         # Blanco
        "header_accent": "81",     # Celeste
    },
    "5": {
        "name": "Sunset Gold (Amber HUD)",
        "banner_color": "214",     # Naranja/Ámbar
        "border_color": "214",     # Naranja
        "accent_color": "220",     # Oro/Amarillo
        "info_color": "7",         # Blanco
        "header_accent": "196",    # Rojo para 
    }
}

# Template dinámico para config.conf de Neofetch
CONFIG_TEMPLATE = """# Custom Premium Neofetch Configuration - Cyberpunk/Hacker HUD
# Autogenerated by customize.py - DO NOT EDIT MANUALLY

print_info() {{
    # ─── HUD CABECERA ───
    prin " "
    prin "$(color {border_color})┌───────────────────────────────────────┐"
    prin "$(color {border_color})│          $(color {header_accent})  {hud_title:<25}   $(color {border_color})│"
    prin "$(color {border_color})├───────────────────────────────────────┤"
    
    # ─── INFORMACIÓN DE SOFTWARE ───
    info "$(color {accent_color})    OS" distro
    info "$(color {accent_color})    KERN" kernel
    info "$(color {accent_color})    UPTM" uptime
    info "$(color {accent_color})    PKGS" packages
    info "$(color {accent_color})    SHLL" shell
    info "$(color {accent_color})    TERM" term
    info "$(color {accent_color})    WMGR" wm
    
    # ─── DIVISOR DE RECURSOS ───
    prin "$(color {border_color})├───────────────────────────────────────┤"
    
    # ─── INFORMACIÓN DE HARDWARE ───
    info "$(color {accent_color})    CPU " cpu
    info "$(color {accent_color})    RAM " memory
    info "$(color {accent_color})    DSK " disk
    
    # ─── PIE DE PANEL Y PALETA DE COLORES ───
    prin "$(color {border_color})├───────────────────────────────────────┤"
    prin "$(color {border_color})│  $(color 1)  $(color 2)  $(color 3)  $(color 4)  $(color 5)  $(color 6)  $(color 7)  $(color 8)  $(color {border_color})  │"
    prin "$(color {border_color})└───────────────────────────────────────┘"
    prin " "
}}

# ─── AJUSTES GENERALES ───
os_arch="on"
kernel_shorthand="on"
distro_shorthand="on"
uptime_shorthand="on"
shell_path="off"
shell_version="off"

# ─── VELOCIDAD Y MARCAS DE CPU ───
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="off"
cpu_speed="on"
cpu_cores="off"
cpu_temp="off"

# ─── TAMAÑO Y DETALLE DE DISCO ───
disk_show=('/')
disk_subtitle="dir"
disk_percent="on"

# ─── FORMATOS DE MEMORIA ───
mem_percent="on"

# ─── DISEÑO Y SEPARADOR ───
separator="  $(color 8)❯$(color {info_color})"

# ─── BARRAS DE PROGRESO DE RECURSOS ───
cpu_display="bar"
memory_display="bar"
disk_display="bar"
battery_display="bar"

bar_char_elapsed="█"
bar_char_total="░"
bar_border="off"
bar_length=12

# ─── AJUSTES DE COLORES ───
colors=({border_color} 7 {accent_color} 8 {info_color})

cpu_colors=({accent_color} 7)
memory_colors=({accent_color} 7)
disk_colors=({accent_color} 7)

# ─── LOGO Y ARTE ASCII ───
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=({banner_color} {header_accent})
ascii_bold="on"
stdout="off"
"""

def print_banner():
    banner = """\033[1;36m
███╗   ██╗███████╗ ██████╗ ███████╗ ██████╗████████╗ ██████╗██╗  ██╗
████╗  ██║██╔════╝██╔═══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝██║  ██║
██╔██╗ ██║█████╗  ██║   ██║█████╗  ██║        ██║   ██║     ███████║
██║╚██╗██║██╔══╝  ██║   ██║██╔══╝  ██║        ██║   ██║     ██╔══██║
██║ ╚████║███████╗╚██████╔╝██║     ╚██████╗   ██║   ╚██████╗██║  ██║
╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝      ╚═════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝
              \033[1;198m[ H A C K E R   C U S T O M I Z E R ]\033[0m
"""
    print(banner)

def get_current_host():
    try:
        import socket
        return socket.gethostname().upper()
    except:
        return "ARCH"

def select_theme():
    print("\n\033[1;35m--- SELECCIONA EL TEMA VISUAL ---\033[0m")
    for key, value in THEMES.items():
        # Display each option in its matching color
        color_ansi = value["banner_color"]
        print(f" [\033[1;32m{key}\033[0m] \033[38;5;{color_ansi}m{value['name']}\033[0m")
    
    choice = input("\nElige una opción [1-5] (Por defecto: 1): ").strip()
    return choice if choice in THEMES else "1"

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Limpiar terminal para una experiencia estética
    print("\033[H\033[2J", end="")
    print_banner()

    # 1. Obtener texto del banner (usando Dune Rise)
    default_text = get_current_host()
    print(f"\033[1;32m[+] Configuración del Título (Fuente Dune Rise)\033[0m")
    banner_text = input(f"Ingresa el texto del banner [A-Z, 0-9] (Por defecto: {default_text}): ").strip().upper()
    if not banner_text:
        banner_text = default_text

    # Limitar texto para que no rompa el diseño del logo
    banner_text = banner_text[:12]

    # 2. Obtener texto del HUD
    print(f"\n\033[1;32m[+] Configuración de Cabecera del Panel HUD\033[0m")
    hud_title = input("Ingresa el texto de la cabecera (Por defecto: CYBERNETIC SYSTEM): ").strip().upper()
    if not hud_title:
        hud_title = "CYBERNETIC SYSTEM"
    hud_title = hud_title[:24]

    # 3. Seleccionar tema
    theme_choice = select_theme()
    theme = THEMES[theme_choice]
    
    print(f"\n\033[1;34m[~] Aplicando tema: {theme['name']}...\033[0m")

    # 4. Escribir el config.conf personalizado
    config_path = os.path.join(base_dir, "config.conf")
    config_content = CONFIG_TEMPLATE.format(
        border_color=theme["border_color"],
        header_accent=theme["header_accent"],
        accent_color=theme["accent_color"],
        info_color=theme["info_color"],
        banner_color=theme["banner_color"],
        hud_title=hud_title
    )
    
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_content)
    
    print("\033[1;32m[+] Archivo config.conf actualizado.\033[0m")

    # 5. Regenerar banner usando generate_banner.py
    generator_path = os.path.join(base_dir, "generate_banner.py")
    banner_txt_path = os.path.join(base_dir, "banner.txt")
    font_relative_path = os.path.join(base_dir, "..", "misc", "fonts", "Dune_Rise.ttf")

    print("\033[1;34m[~] Generando banner de texto con la fuente Dune Rise...\033[0m")
    
    try:
        # Run python process
        subprocess.run([
            sys.executable, generator_path,
            "--text", banner_text,
            "--font", font_relative_path,
            "--output", banner_txt_path,
            "--color", theme["banner_color"]
        ], check=True)
    except Exception as e:
        print(f"\033[1;31m[!] Error al regenerar el banner: {e}\033[0m")

    print("\n\033[1;32m[✔] ¡Configuración personalizada aplicada con éxito!\033[0m")
    print(f"Carpeta: \033[1;35mneofetch-config/\033[0m")
    print(f"  - Configuración: \033[1;36mconfig.conf\033[0m")
    print(f"  - Banner de Fuente: \033[1;36mbanner.txt\033[0m")
    print(f"  - Texto del Logo: '\033[1;32m{banner_text}\033[0m'")
    
    # 6. Preguntar si desea probarlo inmediatamente
    test_run = input("\n¿Quieres probar neofetch con este diseño ahora? [S/n]: ").strip().lower()
    if test_run in ["", "s", "si", "yes", "y"]:
        wrapper_path = os.path.join(base_dir, "neofetch.sh")
        if os.path.exists(wrapper_path):
            print("\n\033[1;34m[~] Ejecutando Neofetch...\033[0m\n")
            try:
                # Execute bash script
                subprocess.run(["bash", wrapper_path])
            except Exception as e:
                # Run neofetch directly as fallback
                try:
                    subprocess.run(["neofetch", "--config", config_path, "--ascii", banner_txt_path])
                except Exception as ex:
                    print(f"\033[1;31m[!] No se pudo ejecutar neofetch. Asegúrate de tenerlo instalado: {ex}\033[0m")
        else:
            # Fallback if wrapper script not yet created
            try:
                subprocess.run(["neofetch", "--config", config_path, "--ascii", banner_txt_path])
            except Exception as ex:
                print(f"\033[1;31m[!] No se pudo ejecutar neofetch: {ex}\033[0m")

if __name__ == "__main__":
    main()
