#!/usr/bin/env python3
import os
import sys
import subprocess

# Temas predefinidos para la interfaz hacker
THEMES = {
    "1": {
        "name": "Toxic Green (Classic Matrix)",
        "banner_color": "82",      # Verde Neón
        "border_color": "82",      # Verde Neón
        "accent_color": "82",      # Verde Neón (Etiquetas)
        "info_color": "7",         # Blanco (Valores)
        "header_accent": "198",    # Rosa Neón para 
    },
    "2": {
        "name": "Cyberpunk Neon (Pink/Cyan)",
        "banner_color": "198",     # Rosa/Magenta Neón
        "border_color": "198",     # Rosa Neón
        "accent_color": "198",     # Rosa Neón (Etiquetas)
        "info_color": "39",        # Cian (Valores)
        "header_accent": "39",     # Cian
    },
    "3": {
        "name": "Blood Red (Deep Net)",
        "banner_color": "196",     # Rojo Sangre
        "border_color": "196",     # Rojo
        "accent_color": "196",     # Rojo (Etiquetas)
        "info_color": "7",         # Blanco (Valores)
        "header_accent": "220",    # Dorado/Amarillo
    },
    "4": {
        "name": "Ghost Cyan (Ice Cold)",
        "banner_color": "51",      # Cian Brillante
        "border_color": "51",      # Cian
        "accent_color": "51",      # Cian (Etiquetas)
        "info_color": "7",         # Blanco (Valores)
        "header_accent": "81",     # Celeste
    },
    "5": {
        "name": "Sunset Gold (Amber HUD)",
        "banner_color": "214",     # Naranja/Ámbar
        "border_color": "214",     # Naranja
        "accent_color": "214",     # Naranja (Etiquetas)
        "info_color": "7",         # Blanco (Valores)
        "header_accent": "220",    # Amarillo
    }
}

# Estilos de iconos
ICON_SETS = {
    "1": {
        "name": "Nerd Fonts Modernos (, , ...)",
        "os": "",
        "kern": "",
        "uptm": "",
        "pkgs": "",
        "shll": "",
        "term": "",
        "wmgr": "",
        "cpu": "",
        "ram": "",
        "dsk": "",
        "dot": ""
    },
    "2": {
        "name": "Geométricos Cyber-Retro (▲, ⚃, ♦...)",
        "os": "▲",
        "kern": "⚃",
        "uptm": "♦",
        "pkgs": "❖",
        "shll": "▣",
        "term": "▣",
        "wmgr": "❖",
        "cpu": "■",
        "ram": "■",
        "dsk": "♦",
        "dot": "●"
    }
}

# Template dinámico para config.conf de Neofetch
# NOTA DE DISEÑO NATIVO: Usamos la sintaxis estándar de Neofetch 'info "etiqueta" modulo'.
# El color de la etiqueta se maneja mediante el tercer color del array 'colors'.
# El color del valor se maneja mediante el quinto color del array 'colors'.
# Esto evita romper la alineación de columnas y permite que Neofetch renderice los valores correctamente.
CONFIG_TEMPLATE = """# Custom Premium Neofetch Configuration - Cyberpunk/Hacker HUD
# Autogenerated by customize.py - DO NOT EDIT MANUALLY

print_info() {{
    # ─── HUD CABECERA ───
    prin " "
    prin "$(color {border_color})┌───────────────────────────────────────┐"
    prin "$(color {border_color})│          $(color {header_accent})  {hud_title:<25}   $(color {border_color})│"
    prin "$(color {border_color})├───────────────────────────────────────┤"
    
    # ─── INFORMACIÓN DE SOFTWARE ───
    info "  {icon_os}  OS" distro
    info "  {icon_kern}  KERN" kernel
    info "  {icon_uptm}  UPTM" uptime
    info "  {icon_pkgs}  PKGS" packages
    info "  {icon_shll}  SHLL" shell
    info "  {icon_term}  TERM" term
    info "  {icon_wmgr}  WMGR" wm
    
    # ─── DIVISOR DE RECURSOS ───
    prin "$(color {border_color})├───────────────────────────────────────┤"
    
    # ─── INFORMACIÓN DE HARDWARE ───
    info "  {icon_cpu}  CPU" cpu
    info "  {icon_ram}  RAM" memory
    info "  {icon_dsk}  DSK" disk
    
    # ─── PIE DE PANEL Y PALETA DE COLORES ───
    prin "$(color {border_color})├───────────────────────────────────────┤"
    prin "$(color {border_color})│  $(color 1){icon_dot}  $(color 2){icon_dot}  $(color 3){icon_dot}  $(color 4){icon_dot}  $(color 5){icon_dot}  $(color 6){icon_dot}  $(color 7){icon_dot}  $(color 8){icon_dot}  $(color {border_color})  │"
    prin "$(color {border_color})└───────────────────────────────────────┘"
    prin " "
}}

# ─── AJUSTES GENERALES ───
os_arch="on"
kernel_shorthand="on"
distro_shorthand="on"
uptime_shorthand="on"
shell_path="off"
shell_version="off"

# ─── VELOCIDAD Y MARCAS DE CPU ───
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="off"
cpu_speed="on"
cpu_cores="off"
cpu_temp="off"

# ─── TAMAÑO Y DETALLE DE DISCO ───
disk_show=('/')
disk_subtitle="dir"
disk_percent="on"

# ─── FORMATOS DE MEMORIA ───
mem_percent="on"

# ─── DISEÑO Y SEPARADOR ───
# El separador es la flecha y fuerza el color del valor siguiente
separator="  $(color 8)❯$(color {info_color})"

# ─── BARRAS DE PROGRESO DE RECURSOS ───
cpu_display="bar"
memory_display="bar"
disk_display="bar"
battery_display="bar"

bar_char_elapsed="█"
bar_char_total="░"
bar_border="off"
bar_length=12

# ─── AJUSTES DE COLORES NATIVOS ───
# Colores: (Título/Borde, Arroba, Etiquetas, Separador, Valores)
colors=({border_color} 7 {accent_color} 8 {info_color})

cpu_colors=({accent_color} 7)
memory_colors=({accent_color} 7)
disk_colors=({accent_color} 7)

# ─── LOGO Y ARTE ASCII ───
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=({banner_color} {header_accent})
ascii_bold="on"
stdout="off"
"""

def print_banner():
    banner = """\033[1;36m
███╗   ██╗███████╗ ██████╗ ███████╗ ██████╗████████╗ ██████╗██╗  ██╗
████╗  ██║██╔════╝██╔═══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝██║  ██║
██╔██╗ ██║█████╗  ██║   ██║█████╗  ██║        ██║   ██║     ███████║
██║╚██╗██║██╔══╝  ██║   ██║██╔══╝  ██║        ██║   ██║     ██╔══██║
██║ ╚████║███████╗╚██████╔╝██║     ╚██████╗   ██║   ╚██████╗██║  ██║
╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝      ╚═════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝
              \033[1;198m[ H A C K E R   C U S T O M I Z E R ]\033[0m
"""
    print(banner)

def get_current_host():
    try:
        import socket
        return socket.gethostname().upper()
    except:
        return "ARCH"

def select_theme():
    print("\n\033[1;35m--- SELECCIONA EL TEMA VISUAL ---\033[0m")
    for key, value in THEMES.items():
        color_ansi = value["banner_color"]
        print(f" [\033[1;32m{key}\033[0m] \033[38;5;{color_ansi}m{value['name']}\033[0m")
    
    choice = input("\nElige una opción [1-5] (Por defecto: 1): ").strip()
    return choice if choice in THEMES else "1"

def select_icons():
    print("\n\033[1;35m--- SELECCIONA EL ESTILO DE ICONOS ---\033[0m")
    for key, value in ICON_SETS.items():
        print(f" [\033[1;32m{key}\033[0m] \033[1;37m{value['name']}\033[0m")
    
    choice = input("\nElige una opción [1-2] (Por defecto: 1): ").strip()
    return choice if choice in ICON_SETS else "1"

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Limpiar terminal para una experiencia estética
    print("\033[H\033[2J", end="")
    print_banner()

    # 1. Obtener texto del banner (usando Dune Rise)
    default_text = get_current_host()
    print(f"\033[1;32m[+] Configuración del Título (Fuente Dune Rise)\033[0m")
    banner_text = input(f"Ingresa el texto del banner [A-Z, 0-9] (Por defecto: {default_text}): ").strip().upper()
    if not banner_text:
        banner_text = default_text
    banner_text = banner_text[:12]

    # 2. Obtener texto del HUD
    print(f"\n\033[1;32m[+] Configuración de Cabecera del Panel HUD\033[0m")
    hud_title = input("Ingresa el texto de la cabecera (Por defecto: CYBERNETIC SYSTEM): ").strip().upper()
    if not hud_title:
        hud_title = "CYBERNETIC SYSTEM"
    hud_title = hud_title[:24]

    # 3. Seleccionar tema de color
    theme_choice = select_theme()
    theme = THEMES[theme_choice]
    
    # 4. Seleccionar estilo de iconos
    icon_choice = select_icons()
    icons = ICON_SETS[icon_choice]
    
    print(f"\n\033[1;34m[~] Aplicando tema y estilo de iconos...\033[0m")

    # 5. Escribir el config.conf personalizado
    config_path = os.path.join(base_dir, "config.conf")
    config_content = CONFIG_TEMPLATE.format(
        border_color=theme["border_color"],
        header_accent=theme["header_accent"],
        accent_color=theme["accent_color"],
        info_color=theme["info_color"],
        banner_color=theme["banner_color"],
        hud_title=hud_title,
        icon_os=icons["os"],
        icon_kern=icons["kern"],
        icon_uptm=icons["uptm"],
        icon_pkgs=icons["pkgs"],
        icon_shll=icons["shll"],
        icon_term=icons["term"],
        icon_wmgr=icons["wmgr"],
        icon_cpu=icons["cpu"],
        icon_ram=icons["ram"],
        icon_dsk=icons["dsk"],
        icon_dot=icons["dot"]
    )
    
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_content)
    
    print("\033[1;32m[+] Archivo config.conf actualizado con sintaxis nativa.\033[0m")

    # 6. Regenerar banner usando generate_banner.py
    generator_path = os.path.join(base_dir, "generate_banner.py")
    banner_txt_path = os.path.join(base_dir, "banner.txt")
    font_relative_path = os.path.join(base_dir, "..", "misc", "fonts", "Dune_Rise.ttf")

    print("\033[1;34m[~] Generando banner de texto con la fuente Dune Rise...\033[0m")
    
    try:
        subprocess.run([
            sys.executable, generator_path,
            "--text", banner_text,
            "--font", font_relative_path,
            "--output", banner_txt_path,
            "--color", theme["banner_color"]
        ], check=True)
    except Exception as e:
        print(f"\033[1;31m[!] Error al regenerar el banner: {e}\033[0m")

    print("\n\033[1;32m[✔] ¡Configuración personalizada aplicada con éxito!\033[0m")
    print(f"Carpeta: \033[1;35mneofetch-config/\033[0m")
    print(f"  - Configuración: \033[1;36mconfig.conf\033[0m")
    print(f"  - Banner de Fuente: \033[1;36mbanner.txt\033[0m")
    print(f"  - Iconos seleccionados: \033[1;32m{icons['name']}\033[0m")
    
    test_run = input("\n¿Quieres probar neofetch con este diseño ahora? [S/n]: ").strip().lower()
    if test_run in ["", "s", "si", "yes", "y"]:
        wrapper_path = os.path.join(base_dir, "neofetch.sh")
        if os.path.exists(wrapper_path):
            print("\n\033[1;34m[~] Ejecutando Neofetch...\033[0m\n")
            try:
                subprocess.run(["bash", wrapper_path])
            except Exception as e:
                try:
                    subprocess.run(["neofetch", "--config", config_path, "--ascii", banner_txt_path])
                except Exception as ex:
                    print(f"\033[1;31m[!] No se pudo ejecutar neofetch: {ex}\033[0m")
        else:
            try:
                subprocess.run(["neofetch", "--config", config_path, "--ascii", banner_txt_path])
            except Exception as ex:
                print(f"\033[1;31m[!] No se pudo ejecutar neofetch: {ex}\033[0m")

if __name__ == "__main__":
    main()
